name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend && npm install

    - name: Fix permissions for react-scripts
      run: |
        cd frontend && chmod +x node_modules/.bin/react-scripts

    - name: Build frontend
      run: |
        cd frontend && npm run build

    - name: Deploy to Azure Web App (Frontend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: todo-app-react 
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./frontend/build
